// printf "$(for f in `ls include/rock`; do printf '#include "rock/'$f'"\n'; done)" | sed -n '1!p'
#include "rock/ast.hh"
#include "rock/class.hh"
#include "rock/eval.hh"
#include "rock/exception.hh"
#include "rock/file.hh"
#include "rock/globals.hh"
#include "rock/lexer.hh"
#include "rock/nil.hh"
#include "rock/number.hh"
#include "rock/parser.hh"
#include "rock/reference.hh"
#include "rock/result.hh"
#include "rock/scope.hh"
#include "rock/stack.hh"
#include "rock/string.hh"
#include "rock/value.hh"
